// frontend/src/components/SettingsView.tsx
import { useState, useMemo, useEffect, useCallback, useRef } from 'react'
import { useAuth } from '@/hooks/useAuth'
import { useLlmConfigs } from '@/hooks/useLlmConfigs'
import { useOrbitStore } from '@/stores/useOrbitStore'
import { llmConfigApi } from '@/api/llmConfigs'
import type { LlmConfig, LlmProvider, LlmModel } from '@/api/types'
import './SettingsView.css'

const FALLBACK_PROVIDERS: LlmProvider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
    default_base_url: 'https://api.openai.com/v1',
  },
  {
    id: 'openai_compatible',
    name: 'OpenAI Compatible',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
  },
  {
    id: 'anthropic',
    name: 'Claude / Anthropic',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    requires_api_key: true,
    supports_custom_base_url: false,
    supports_model_list: true,
  },
  {
    id: 'ollama',
    name: 'Ollama',
    requires_api_key: false,
    supports_custom_base_url: true,
    supports_model_list: true,
    default_base_url: 'http://127.0.0.1:11434',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
    default_base_url: 'https://api.deepseek.com',
  },
  {
    id: 'qwen',
    name: 'Qwen',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
    default_base_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  },
]

interface ConfigForm {
  name: string
  provider: string
  model: string
  base_url: string
  api_key: string
  provider_options: string
  is_default: boolean
}

const defaultForm: ConfigForm = {
  name: '',
  provider: '',
  model: '',
  base_url: '',
  api_key: '',
  provider_options: '',
  is_default: false,
}

export function SettingsView() {
  const { hasUser } = useAuth()
  const {
    configs,
    providers: apiProviders,
    isLoadingConfigs,
    isLoadingProviders,
    createConfig,
    updateConfig,
    archiveConfig: archiveConfigMutation,
    setDefaultConfig: setDefaultConfigMutation,
    isSaving,
  } = useLlmConfigs(hasUser)

  const errorMessage = useOrbitStore((s) => s.errorMessage)
  const setErrorMessage = useOrbitStore((s) => s.setErrorMessage)

  const [showForm, setShowForm] = useState(false)
  const [editingConfigId, setEditingConfigId] = useState<string | null>(null)
  const [formError, setFormError] = useState('')
  const [providerList, setProviderList] = useState<LlmProvider[]>([])
  const [modelOptions, setModelOptions] = useState<LlmModel[]>([])
  const [modelStatus, setModelStatus] = useState('')
  const [isLoadingModels, setIsLoadingModels] = useState(false)
  const [configForm, setConfigForm] = useState<ConfigForm>({ ...defaultForm })

  const providers = useMemo(
    () => (providerList.length > 0 ? providerList : FALLBACK_PROVIDERS),
    [providerList],
  )

  const selectedProvider = useMemo(
    () => providers.find((p) => p.id === configForm.provider),
    [providers, configForm.provider],
  )

  const modelOptionIds = useMemo(
    () => modelOptions.map((m) => m.id).filter(Boolean),
    [modelOptions],
  )

  const canFetchModels = useMemo(() => {
    if (!selectedProvider?.supports_model_list || isLoadingModels) return false
    if (editingConfigId) {
      const editingConfig = configs.find((c) => c.id === editingConfigId)
      if (editingConfig?.has_api_key && !configForm.api_key.trim()) return true
    }
    if (selectedProvider?.requires_api_key === false) return true
    return Boolean(configForm.api_key.trim())
  }, [selectedProvider, isLoadingModels, editingConfigId, configs, configForm.api_key])

  const resetForm = useCallback(() => {
    setConfigForm({ ...defaultForm })
    setEditingConfigId(null)
    setFormError('')
    setModelOptions([])
    setModelStatus('')
    setShowForm(false)
  }, [])

  const startCreate = useCallback(() => {
    resetForm()
    const activeProviders = providers
    if (activeProviders.length > 0) {
      const p = activeProviders[0]
      setConfigForm((prev) => ({
        ...prev,
        provider: p.id,
        base_url: p.default_base_url && !prev.base_url ? p.default_base_url : '',
      }))
    }
    setShowForm(true)
  }, [resetForm, providers])

  const startEdit = useCallback((config: LlmConfig) => {
    setConfigForm({
      name: config.name || '',
      provider: config.provider || '',
      model: config.model || '',
      base_url: config.base_url || '',
      api_key: '',
      provider_options: config.provider_options
        ? JSON.stringify(config.provider_options, null, 2)
        : '',
      is_default: Boolean(config.is_default),
    })
    setEditingConfigId(config.id)
    setFormError('')
    setModelOptions([])
    setModelStatus('')
    setShowForm(true)
  }, [])

  const parseProviderOptions = useCallback((): Record<string, unknown> | null => {
    const raw = configForm.provider_options.trim()
    if (!raw) return {}
    try {
      const parsed = JSON.parse(raw)
      if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') {
        setFormError('Provider Options must be a JSON object.')
        return null
      }
      return parsed
    } catch {
      setFormError('Provider Options is not valid JSON.')
      return null
    }
  }, [configForm.provider_options])

  const formatProviderOptions = useCallback(() => {
    setFormError('')
    const parsed = parseProviderOptions()
    if (parsed === null) return
    setConfigForm((prev) => ({ ...prev, provider_options: JSON.stringify(parsed, null, 2) }))
  }, [parseProviderOptions])

  const fetchModels = useCallback(async () => {
    setFormError('')
    setModelStatus('')
    setModelOptions([])

    const providerOptions = parseProviderOptions()
    if (providerOptions === null) return

    setIsLoadingModels(true)
    try {
      let models: LlmModel[]
      if (editingConfigId) {
        const editingConfig = configs.find((c) => c.id === editingConfigId)
        if (editingConfig?.has_api_key && !configForm.api_key.trim()) {
          models = await llmConfigApi.configModels(editingConfigId)
        } else {
          models = await llmConfigApi.models({
            provider: configForm.provider,
            base_url: configForm.base_url.trim() || null,
            api_key: configForm.api_key.trim() || null,
            provider_options: providerOptions,
          })
        }
      } else {
        models = await llmConfigApi.models({
          provider: configForm.provider,
          base_url: configForm.base_url.trim() || null,
          api_key: configForm.api_key.trim() || null,
          provider_options: providerOptions,
        })
      }
      setModelOptions(models || [])
      setModelStatus(
        models.length > 0 ? `${models.length} models loaded.` : 'No models returned.',
      )
    } catch (error) {
      setModelStatus('')
      setFormError(error instanceof Error ? error.message : String(error))
    } finally {
      setIsLoadingModels(false)
    }
  }, [
    configForm,
    editingConfigId,
    configs,
    parseProviderOptions,
  ])

  const submitConfig = useCallback(async () => {
    setFormError('')
    const payload: {
      name: string
      provider: string
      model: string
      is_default: boolean
      base_url?: string
      api_key?: string
      provider_options?: Record<string, unknown>
    } = {
      name: configForm.name.trim(),
      provider: configForm.provider.trim(),
      model: configForm.model.trim(),
      is_default: configForm.is_default,
    }

    if (configForm.base_url.trim()) {
      payload.base_url = configForm.base_url.trim()
    }
    if (configForm.api_key.trim()) {
      payload.api_key = configForm.api_key.trim()
    }
    const providerOptions = parseProviderOptions()
    if (providerOptions === null) return
    payload.provider_options = providerOptions

    let result: LlmConfig | null = null
    try {
      if (editingConfigId) {
        result = await updateConfig(editingConfigId, payload)
      } else {
        result = await createConfig(payload)
      }
    } catch (error) {
      setFormError(error instanceof Error ? error.message : String(error))
      return
    }

    if (result) {
      resetForm()
    }
  }, [configForm, editingConfigId, createConfig, updateConfig, resetForm, parseProviderOptions])

  const handleDelete = useCallback(
    async (config: LlmConfig) => {
      if (!confirm(`Archive "${config.name}"?`)) return
      try {
        await archiveConfigMutation(config.id)
      } catch (error) {
        setErrorMessage(error instanceof Error ? error.message : String(error))
      }
    },
    [archiveConfigMutation, setErrorMessage],
  )

  const handleSetDefault = useCallback(
    async (configId: string) => {
      try {
        await setDefaultConfigMutation(configId)
      } catch (error) {
        setErrorMessage(error instanceof Error ? error.message : String(error))
      }
    },
    [setDefaultConfigMutation, setErrorMessage],
  )

  const providerOptionsPreview = useCallback(
    (options: Record<string, unknown> | null | undefined) => {
      if (!options || Object.keys(options).length === 0) return null
      const keys = Object.keys(options)
      if (keys.length <= 2) {
        return keys.map((k) => `${k}: ${options[k]}`).join(', ')
      }
      return `${keys.length} options`
    },
    [],
  )

  useEffect(() => {
    const loadProviders = async () => {
      if (!hasUser) return
      try {
        const list = await llmConfigApi.providers()
        setProviderList(list)
      } catch {
        setProviderList(FALLBACK_PROVIDERS)
      }
    }
    loadProviders()
  }, [hasUser])

  useEffect(() => {
    if (configForm.provider) {
      setModelOptions([])
      setModelStatus('')
      const provider = selectedProvider
      if (!provider) return
      if (provider.default_base_url && !configForm.base_url.trim()) {
        setConfigForm((prev) => ({ ...prev, base_url: provider.default_base_url! }))
      }
      if (provider.supports_custom_base_url === false) {
        setConfigForm((prev) => ({ ...prev, base_url: '' }))
      }
    }
  }, [configForm.provider])

  const editingConfig = useMemo(
    () => (editingConfigId ? configs.find((c) => c.id === editingConfigId) : null),
    [editingConfigId, configs],
  )

  return (
    <main className="chat-shell">
      <header className="mobile-header">
        <strong>Orbit</strong>
      </header>

      <section className="chat-canvas" aria-label="Model configurations">
        <div className="canvas-bar">
          <button type="button" className="model-button">
            <span>Model Configs</span>
          </button>
          <div style={{ marginLeft: 'auto' }}>
            <button
              type="button"
              className="primary-button"
              style={{ width: 'auto', padding: '0 24px' }}
              onClick={startCreate}
            >
              <span className="material-symbols-outlined" aria-hidden="true">add</span>
              <span>New Config</span>
            </button>
          </div>
        </div>

        <div className="chat-stream">
          {errorMessage && <p className="status-message error">{errorMessage}</p>}

          {!isLoadingConfigs && configs.length === 0 && (
            <p className="status-message">
              No model configurations yet. Create one to start chatting.
            </p>
          )}

          {configs.map((config) => (
            <div key={config.id} className="config-card">
              <div className="config-header">
                <span className="config-name">{config.name}</span>
                {config.is_default && <span className="config-badge">Default</span>}
                {!config.is_enabled && (
                  <span className="config-badge config-badge-disabled">Disabled</span>
                )}
              </div>
              <div className="config-meta">
                <span>
                  <strong>Provider:</strong> {config.provider}
                </span>
                <span>
                  <strong>Model:</strong> {config.model}
                </span>
                {config.base_url && (
                  <span>
                    <strong>Base URL:</strong> {config.base_url}
                  </span>
                )}
                {config.has_api_key && (
                  <span>
                    <strong>API Key:</strong> ••••••••
                  </span>
                )}
              </div>
              {providerOptionsPreview(config.provider_options) && (
                <div className="config-options-preview">
                  {providerOptionsPreview(config.provider_options)}
                </div>
              )}
              <div className="config-actions">
                <button
                  type="button"
                  className="text-button"
                  style={{ width: 'auto' }}
                  onClick={() => startEdit(config)}
                >
                  Edit
                </button>
                {!config.is_default && (
                  <button
                    type="button"
                    className="text-button"
                    style={{ width: 'auto' }}
                    onClick={() => handleSetDefault(config.id)}
                  >
                    Set Default
                  </button>
                )}
                <button
                  type="button"
                  className="text-button"
                  style={{ width: 'auto', color: 'var(--ink-soft)' }}
                  onClick={() => handleDelete(config)}
                >
                  Archive
                </button>
              </div>
            </div>
          ))}

          {showForm && (
            <div className="config-form-panel">
              <h2>{editingConfigId ? 'Edit Config' : 'New Config'}</h2>
              <form
                className="auth-form"
                onSubmit={(e) => {
                  e.preventDefault()
                  submitConfig()
                }}
              >
                <label>
                  <span>Name</span>
                  <input
                    value={configForm.name}
                    onChange={(e) =>
                      setConfigForm((prev) => ({ ...prev, name: e.target.value }))
                    }
                    placeholder="My OpenAI Config"
                    required
                  />
                </label>
                <label>
                  <span>Provider</span>
                  <select
                    value={configForm.provider}
                    onChange={(e) =>
                      setConfigForm((prev) => ({ ...prev, provider: e.target.value }))
                    }
                    required
                  >
                    {isLoadingProviders && (
                      <option disabled value="">
                        Loading providers
                      </option>
                    )}
                    {providers.map((provider) => (
                      <option key={provider.id} value={provider.id}>
                        {provider.name || provider.id}
                      </option>
                    ))}
                  </select>
                </label>
                <label>
                  <span>Model</span>
                  <div className="model-picker-row">
                    <input
                      value={configForm.model}
                      onChange={(e) =>
                        setConfigForm((prev) => ({ ...prev, model: e.target.value }))
                      }
                      placeholder="Enter or fetch a model"
                      list="model-list"
                      required
                    />
                    <button
                      type="button"
                      className="icon-form-button"
                      disabled={!canFetchModels}
                      title="Fetch models"
                      onClick={fetchModels}
                    >
                      <span className="material-symbols-outlined" aria-hidden="true">sync</span>
                    </button>
                  </div>
                  <datalist id="model-list">
                    {modelOptionIds.map((id) => (
                      <option key={id} value={id} />
                    ))}
                  </datalist>
                </label>
                <label>
                  <span>Base URL (optional)</span>
                  <input
                    value={configForm.base_url}
                    onChange={(e) =>
                      setConfigForm((prev) => ({ ...prev, base_url: e.target.value }))
                    }
                    disabled={selectedProvider?.supports_custom_base_url === false}
                    placeholder={
                      selectedProvider?.default_base_url || 'https://api.openai.com/v1'
                    }
                  />
                </label>
                <label>
                  <span>
                    API Key (optional
                    {editingConfigId && editingConfig?.has_api_key
                      ? ', leave blank to keep current'
                      : ''}
                    )
                  </span>
                  <input
                    value={configForm.api_key}
                    onChange={(e) =>
                      setConfigForm((prev) => ({ ...prev, api_key: e.target.value }))
                    }
                    type="password"
                    placeholder="sk-..."
                  />
                </label>
                <label>
                  <span>Provider Options (JSON, optional)</span>
                  <textarea
                    value={configForm.provider_options}
                    onChange={(e) =>
                      setConfigForm((prev) => ({
                        ...prev,
                        provider_options: e.target.value,
                      }))
                    }
                    rows={4}
                    placeholder='{"generation": {"temperature": 0.7}, "connection": {"timeout": 60}}'
                  ></textarea>
                </label>
                <div className="form-inline-actions">
                  <button
                    type="button"
                    className="text-button compact"
                    onClick={formatProviderOptions}
                  >
                    Format JSON
                  </button>
                </div>
                <label className="checkbox-field">
                  <input
                    checked={configForm.is_default}
                    onChange={(e) =>
                      setConfigForm((prev) => ({
                        ...prev,
                        is_default: e.target.checked,
                      }))
                    }
                    type="checkbox"
                  />
                  <span>Use as default model</span>
                </label>

                {modelStatus && <p className="status-message">{modelStatus}</p>}
                {formError && <p className="status-message error">{formError}</p>}

                <button type="submit" className="primary-button" disabled={isSaving}>
                  <span className="material-symbols-outlined" aria-hidden="true">save</span>
                  <span>
                    {isSaving
                      ? 'Saving'
                      : editingConfigId
                        ? 'Save Changes'
                        : 'Create Config'}
                  </span>
                </button>
                <button type="button" className="text-button" onClick={resetForm}>
                  Cancel
                </button>
              </form>
            </div>
          )}
        </div>
      </section>
    </main>
  )
}

// frontend/src/components/SettingsView.vue
<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { llmConfigApi } from '../api'
import { useOrbit } from '../composables/useOrbit'

const {
  llmConfigs,
  isSaving,
  errorMessage,
  loadLlmConfigs,
  createLlmConfig,
  updateLlmConfig,
  archiveLlmConfig,
  setDefaultLlmConfig,
} = useOrbit()

const FALLBACK_PROVIDERS = [
  {
    id: 'openai',
    name: 'OpenAI',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
    default_base_url: 'https://api.openai.com/v1',
  },
  {
    id: 'openai_compatible',
    name: 'OpenAI Compatible',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
  },
  {
    id: 'anthropic',
    name: 'Claude / Anthropic',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    requires_api_key: true,
    supports_custom_base_url: false,
    supports_model_list: true,
  },
  {
    id: 'ollama',
    name: 'Ollama',
    requires_api_key: false,
    supports_custom_base_url: true,
    supports_model_list: true,
    default_base_url: 'http://127.0.0.1:11434',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
    default_base_url: 'https://api.deepseek.com',
  },
  {
    id: 'qwen',
    name: 'Qwen',
    requires_api_key: true,
    supports_custom_base_url: true,
    supports_model_list: true,
    default_base_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
  },
]

const showForm = ref(false)
const editingConfigId = ref(null)
const formError = ref('')
const providerList = ref([])
const modelOptions = ref([])
const modelStatus = ref('')
const isLoadingProviders = ref(false)
const isLoadingModels = ref(false)
const configForm = ref({
  name: '',
  provider: '',
  model: '',
  base_url: '',
  api_key: '',
  provider_options: '',
  is_default: false,
})

const isEditing = computed(() => editingConfigId.value !== null)

const editingConfig = computed(() =>
  editingConfigId.value ? llmConfigs.value.find((c) => c.id === editingConfigId.value) : null,
)

const providers = computed(() => (providerList.value.length > 0 ? providerList.value : FALLBACK_PROVIDERS))

const selectedProvider = computed(() =>
  providers.value.find((provider) => provider.id === configForm.value.provider),
)

const modelOptionIds = computed(() => modelOptions.value.map((model) => model.id).filter(Boolean))

const canFetchModels = computed(() => {
  if (!selectedProvider.value?.supports_model_list || isLoadingModels.value) return false
  if (isEditing.value && editingConfig.value?.has_api_key && !configForm.value.api_key.trim()) return true
  if (selectedProvider.value?.requires_api_key === false) return true
  return Boolean(configForm.value.api_key.trim())
})

const resetForm = () => {
  configForm.value = {
    name: '',
    provider: '',
    model: '',
    base_url: '',
    api_key: '',
    provider_options: '',
    is_default: false,
  }
  editingConfigId.value = null
  formError.value = ''
  modelOptions.value = []
  modelStatus.value = ''
  showForm.value = false
}

const startCreate = () => {
  resetForm()
  if (providers.value.length > 0) {
    configForm.value.provider = providers.value[0].id
    applyProviderDefaultBaseUrl()
  }
  showForm.value = true
}

const startEdit = (config) => {
  configForm.value = {
    name: config.name || '',
    provider: config.provider || '',
    model: config.model || '',
    base_url: config.base_url || '',
    api_key: '',
    provider_options: config.provider_options ? JSON.stringify(config.provider_options, null, 2) : '',
    is_default: Boolean(config.is_default),
  }
  editingConfigId.value = config.id
  formError.value = ''
  modelOptions.value = []
  modelStatus.value = ''
  showForm.value = true
}

const loadProviders = async () => {
  isLoadingProviders.value = true
  try {
    providerList.value = await llmConfigApi.providers()
    if (showForm.value && !configForm.value.provider && providers.value.length > 0) {
      configForm.value.provider = providers.value[0].id
      applyProviderDefaultBaseUrl()
    }
  } catch (error) {
    console.warn(error)
    providerList.value = FALLBACK_PROVIDERS
  } finally {
    isLoadingProviders.value = false
  }
}

const applyProviderDefaultBaseUrl = () => {
  const provider = selectedProvider.value
  if (!provider) return
  if (provider.default_base_url && !configForm.value.base_url.trim()) {
    configForm.value.base_url = provider.default_base_url
  }
  if (provider.supports_custom_base_url === false) {
    configForm.value.base_url = ''
  }
}

const parseProviderOptions = () => {
  const rawOptions = configForm.value.provider_options.trim()
  if (!rawOptions) return {}
  try {
    const parsed = JSON.parse(rawOptions)
    if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') {
      formError.value = 'Provider Options must be a JSON object.'
      return null
    }
    return parsed
  } catch {
    formError.value = 'Provider Options is not valid JSON.'
    return null
  }
}

const formatProviderOptions = () => {
  formError.value = ''
  const parsed = parseProviderOptions()
  if (parsed === null) return
  configForm.value.provider_options = JSON.stringify(parsed, null, 2)
}

const fetchModels = async () => {
  formError.value = ''
  modelStatus.value = ''
  modelOptions.value = []

  const providerOptions = parseProviderOptions()
  if (providerOptions === null) return

  isLoadingModels.value = true
  try {
    let models
    if (isEditing.value && editingConfig.value?.has_api_key && !configForm.value.api_key.trim()) {
      models = await llmConfigApi.configModels(editingConfigId.value)
    } else {
      models = await llmConfigApi.models({
        provider: configForm.value.provider,
        base_url: configForm.value.base_url.trim() || null,
        api_key: configForm.value.api_key.trim() || null,
        provider_options: providerOptions,
      })
    }
    modelOptions.value = models || []
    modelStatus.value = modelOptions.value.length > 0 ? `${modelOptions.value.length} models loaded.` : 'No models returned.'
  } catch (error) {
    modelStatus.value = ''
    formError.value = error instanceof Error ? error.message : String(error)
  } finally {
    isLoadingModels.value = false
  }
}

const submitConfig = async () => {
  formError.value = ''
  const payload = {
    name: configForm.value.name.trim(),
    provider: configForm.value.provider.trim(),
    model: configForm.value.model.trim(),
    is_default: configForm.value.is_default,
  }

  if (configForm.value.base_url.trim()) {
    payload.base_url = configForm.value.base_url.trim()
  }

  if (configForm.value.api_key.trim()) {
    payload.api_key = configForm.value.api_key.trim()
  }

  const providerOptions = parseProviderOptions()
  if (providerOptions === null) return
  payload.provider_options = providerOptions

  let result
  if (isEditing.value) {
    result = await updateLlmConfig(editingConfigId.value, payload)
  } else {
    result = await createLlmConfig(payload)
  }

  if (result) {
    resetForm()
  }
}

const handleDelete = async (config) => {
  if (!confirm(`Archive "${config.name}"?`)) return
  await archiveLlmConfig(config.id)
}

const handleSetDefault = async (config) => {
  await setDefaultLlmConfig(config.id)
}

const providerOptionsPreview = (options) => {
  if (!options || Object.keys(options).length === 0) return null
  const keys = Object.keys(options)
  if (keys.length <= 2) {
    return keys.map((k) => `${k}: ${options[k]}`).join(', ')
  }
  return `${keys.length} options`
}

watch(
  () => configForm.value.provider,
  () => {
    modelOptions.value = []
    modelStatus.value = ''
    applyProviderDefaultBaseUrl()
  },
)

onMounted(loadProviders)
</script>

<template>
  <main class="chat-shell">
    <header class="mobile-header">
      <strong>Orbit</strong>
    </header>

    <section class="chat-canvas" aria-label="Model configurations">
      <div class="canvas-bar">
        <button type="button" class="model-button">
          <span>Model Configs</span>
        </button>
        <div style="margin-left: auto">
          <button type="button" class="primary-button" style="width: auto; padding: 0 24px" @click="startCreate">
            <span class="material-symbols-outlined" aria-hidden="true">add</span>
            <span>New Config</span>
          </button>
        </div>
      </div>

      <div class="chat-stream">
        <p v-if="errorMessage" class="status-message error">{{ errorMessage }}</p>

        <p v-if="llmConfigs.length === 0" class="status-message">
          No model configurations yet. Create one to start chatting.
        </p>

        <div
          v-for="config in llmConfigs"
          :key="config.id"
          class="config-card"
        >
          <div class="config-header">
            <span class="config-name">{{ config.name }}</span>
            <span v-if="config.is_default" class="config-badge">Default</span>
            <span v-if="!config.is_enabled" class="config-badge config-badge-disabled">Disabled</span>
          </div>
          <div class="config-meta">
            <span><strong>Provider:</strong> {{ config.provider }}</span>
            <span><strong>Model:</strong> {{ config.model }}</span>
            <span v-if="config.base_url"><strong>Base URL:</strong> {{ config.base_url }}</span>
            <span v-if="config.has_api_key"><strong>API Key:</strong> ••••••••</span>
          </div>
          <div v-if="providerOptionsPreview(config.provider_options)" class="config-options-preview">
            {{ providerOptionsPreview(config.provider_options) }}
          </div>
          <div class="config-actions">
            <button type="button" class="text-button" style="width: auto" @click="startEdit(config)">Edit</button>
            <button
              v-if="!config.is_default"
              type="button"
              class="text-button"
              style="width: auto"
              @click="handleSetDefault(config)"
            >
              Set Default
            </button>
            <button type="button" class="text-button" style="width: auto; color: var(--ink-soft)" @click="handleDelete(config)">Archive</button>
          </div>
        </div>

        <div v-if="showForm" class="config-form-panel">
          <h2>{{ isEditing ? 'Edit Config' : 'New Config' }}</h2>
          <form class="auth-form" @submit.prevent="submitConfig">
            <label>
              <span>Name</span>
              <input v-model="configForm.name" placeholder="My OpenAI Config" required />
            </label>
            <label>
              <span>Provider</span>
              <select v-model="configForm.provider" required>
                <option v-if="isLoadingProviders" disabled value="">Loading providers</option>
                <option v-for="provider in providers" :key="provider.id" :value="provider.id">
                  {{ provider.name || provider.id }}
                </option>
              </select>
            </label>
            <label>
              <span>Model</span>
              <div class="model-picker-row">
                <input v-model="configForm.model" placeholder="Enter or fetch a model" list="model-list" required />
                <button type="button" class="icon-form-button" :disabled="!canFetchModels" title="Fetch models" @click="fetchModels">
                  <span class="material-symbols-outlined" aria-hidden="true">sync</span>
                </button>
              </div>
              <datalist id="model-list">
                <option v-for="model in modelOptionIds" :key="model" :value="model" />
              </datalist>
            </label>
            <label>
              <span>Base URL (optional)</span>
              <input
                v-model="configForm.base_url"
                :disabled="selectedProvider?.supports_custom_base_url === false"
                :placeholder="selectedProvider?.default_base_url || 'https://api.openai.com/v1'"
              />
            </label>
            <label>
              <span>API Key (optional{{ isEditing && editingConfig?.has_api_key ? ', leave blank to keep current' : '' }})</span>
              <input v-model="configForm.api_key" type="password" placeholder="sk-..." />
            </label>
            <label>
              <span>Provider Options (JSON, optional)</span>
              <textarea
                v-model="configForm.provider_options"
                rows="4"
                placeholder='{"generation": {"temperature": 0.7}, "connection": {"timeout": 60}}'
              ></textarea>
            </label>
            <div class="form-inline-actions">
              <button type="button" class="text-button compact" @click="formatProviderOptions">Format JSON</button>
            </div>
            <label class="checkbox-field">
              <input v-model="configForm.is_default" type="checkbox" />
              <span>Use as default model</span>
            </label>

            <p v-if="modelStatus" class="status-message">{{ modelStatus }}</p>
            <p v-if="formError" class="status-message error">{{ formError }}</p>

            <button type="submit" class="primary-button" :disabled="isSaving">
              <span class="material-symbols-outlined" aria-hidden="true">save</span>
              <span>{{ isSaving ? 'Saving' : isEditing ? 'Save Changes' : 'Create Config' }}</span>
            </button>
            <button type="button" class="text-button" @click="resetForm">Cancel</button>
          </form>
        </div>
      </div>
    </section>
  </main>
</template>

<style scoped>
.config-card {
  padding: 24px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--surface);
}

.config-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 12px;
}

.config-name {
  font-family: "Noto Serif", Georgia, serif;
  font-size: 18px;
  font-weight: 600;
  color: var(--ink);
}

.config-badge {
  padding: 2px 10px;
  border-radius: 999px;
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  background: var(--primary);
  color: var(--on-primary);
}

.config-badge-disabled {
  background: var(--surface-mid);
  color: var(--ink-soft);
}

.config-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 20px;
  margin-bottom: 12px;
  color: var(--ink-muted);
  font-size: 13px;
  line-height: 1.6;
}

.config-actions {
  display: flex;
  gap: 8px;
  padding-top: 12px;
  border-top: 1px solid var(--line);
}

.config-form-panel {
  padding: 32px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--surface);
}

.config-form-panel h2 {
  margin: 0 0 24px;
  font-family: "Noto Serif", Georgia, serif;
  font-size: 22px;
  font-weight: 600;
  color: var(--ink);
}

.config-form-panel textarea {
  width: 100%;
  min-height: 80px;
  padding: 11px 14px;
  border: 1px solid var(--line);
  border-radius: 6px;
  outline: 0;
  background: var(--surface);
  color: var(--ink);
  font: inherit;
  font-size: 14px;
  resize: vertical;
  transition: border-color 180ms ease, box-shadow 180ms ease;
}

.config-form-panel select {
  width: 100%;
  min-height: 48px;
  padding: 0 14px;
  border: 1px solid var(--line);
  border-radius: 6px;
  outline: 0;
  background: var(--surface);
  color: var(--ink);
  font: inherit;
  transition: border-color 180ms ease, box-shadow 180ms ease;
}

.config-form-panel select:focus {
  border-color: var(--primary);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--primary) 12%, transparent);
}

.config-form-panel textarea:focus {
  border-color: var(--primary);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--primary) 12%, transparent);
}

.model-picker-row {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 48px;
  gap: 8px;
}

.icon-form-button {
  display: grid;
  min-width: 48px;
  min-height: 48px;
  place-items: center;
  border: 1px solid var(--line);
  border-radius: 6px;
  background: var(--surface);
  color: var(--ink);
}

.icon-form-button:hover:not(:disabled) {
  border-color: var(--primary);
}

.form-inline-actions {
  display: flex;
  justify-content: flex-end;
  margin-top: -10px;
}

.text-button.compact {
  width: auto;
  margin-top: 0;
  padding: 0;
  font-size: 13px;
}

.checkbox-field {
  display: flex !important;
  align-items: center;
  gap: 10px !important;
}

.checkbox-field input {
  width: 18px;
  min-height: 18px;
}

.checkbox-field span {
  letter-spacing: 0 !important;
  text-transform: none !important;
}

.config-options-preview {
  margin-bottom: 12px;
  padding: 8px 12px;
  border-radius: 4px;
  background: var(--surface-low);
  color: var(--ink-soft);
  font-size: 12px;
  font-family: monospace;
}
</style>
