// frontend/src/components/SideNav.vue
<script setup>
import { ref, nextTick, onMounted, onUnmounted } from 'vue'
import { useOrbit } from '../composables/useOrbit'

const {
  activeView,
  user,
  sortedConversations,
  activeConversationId,
  isBooting,
  displayName,
  accountInitial,
  setActiveView,
  logout,
  openAuth,
  createNewThread,
  selectConversation,
  formatConversationTitle,
  renameConversation,
  archiveConversation,
} = useOrbit()

const editingThreadId = ref(null)
const editingTitle = ref('')
const editInputRef = ref(null)
const showAccountMenu = ref(false)
const accountBtnRef = ref(null)

const startRename = (conversation, event) => {
  event.stopPropagation()
  editingThreadId.value = conversation.id
  editingTitle.value = conversation.title || ''
  nextTick(() => {
    editInputRef.value?.focus()
    editInputRef.value?.select()
  })
}

const submitRename = async () => {
  const title = editingTitle.value.trim()
  if (title && editingThreadId.value) {
    await renameConversation(editingThreadId.value, title)
  }
  cancelEdit()
}

const cancelEdit = () => {
  editingThreadId.value = null
  editingTitle.value = ''
}

const handleDelete = async (conversation, event) => {
  event.stopPropagation()
  if (!confirm(`Archive "${formatConversationTitle(conversation)}"?`)) return
  await archiveConversation(conversation.id)
}

const toggleAccountMenu = () => {
  if (!user.value) {
    openAuth()
    return
  }
  showAccountMenu.value = !showAccountMenu.value
}

const handleMenuAction = (action) => {
  showAccountMenu.value = false
  action()
}

const onClickOutside = (event) => {
  if (showAccountMenu.value && accountBtnRef.value && !accountBtnRef.value.contains(event.target)) {
    showAccountMenu.value = false
  }
}

onMounted(() => document.addEventListener('click', onClickOutside))
onUnmounted(() => document.removeEventListener('click', onClickOutside))
</script>

<template>
  <aside class="side-nav" aria-label="Primary navigation">
    <div class="brand-panel">
      <h1>Orbit</h1>
      <p>Zen AI Assistant</p>
    </div>

    <div class="nav-action">
      <button type="button" class="primary-button" @click="createNewThread()">
        <span class="material-symbols-outlined" aria-hidden="true">add</span>
        <span>New Chat</span>
      </button>
    </div>

    <nav class="nav-list" aria-label="Workspace">
      <div class="thread-section-title">Chats</div>
      <div class="thread-list" aria-label="Recent conversations">
        <div
          v-for="conversation in sortedConversations"
          :key="conversation.id"
          class="thread-item"
          :class="{ active: conversation.id === activeConversationId }"
        >
          <template v-if="editingThreadId === conversation.id">
            <input
              ref="editInputRef"
              v-model="editingTitle"
              class="thread-edit-input"
              @keydown.enter="submitRename()"
              @keydown.escape="cancelEdit()"
              @blur="submitRename()"
              @click.stop
            />
          </template>
          <template v-else>
            <button type="button" class="thread-button" @click="selectConversation(conversation.id)">
              {{ formatConversationTitle(conversation) }}
            </button>
            <div class="thread-actions">
              <button
                type="button"
                class="thread-action-btn"
                aria-label="Rename"
                title="Rename"
                @click="startRename(conversation, $event)"
              >
                <span class="material-symbols-outlined">edit</span>
              </button>
              <button
                type="button"
                class="thread-action-btn thread-action-delete"
                aria-label="Archive"
                title="Archive"
                @click="handleDelete(conversation, $event)"
              >
                <span class="material-symbols-outlined">close</span>
              </button>
            </div>
          </template>
        </div>
        <p v-if="isBooting">Loading workspace...</p>
        <p v-else-if="!user">Sign in to sync chats</p>
        <p v-else-if="sortedConversations.length === 0">No conversations yet</p>
      </div>

      <button
        type="button"
        :class="['nav-item', { active: activeView === 'library' }]"
        @click="setActiveView('library')"
      >
        <span class="material-symbols-outlined" aria-hidden="true">book_2</span>
        <span>Library</span>
      </button>
    </nav>

    <div class="account-section" ref="accountBtnRef">
      <button type="button" class="account-button" @click="toggleAccountMenu">
        <span class="avatar" aria-hidden="true">{{ user ? accountInitial : '?' }}</span>
        <span class="account-copy">
          <strong>{{ displayName }}</strong>
          <small>{{ user ? 'Sign out' : 'Sign in' }}</small>
        </span>
        <span class="material-symbols-outlined" aria-hidden="true">
          <template v-if="user">{{ showAccountMenu ? 'expand_less' : 'expand_more' }}</template>
          <template v-else>login</template>
        </span>
      </button>

      <div v-if="showAccountMenu && user" class="account-menu">
        <button
          type="button"
          class="account-menu-item"
          @click="handleMenuAction(() => setActiveView('library'))"
        >
          <span class="material-symbols-outlined">tune</span>
          <span>LLM Configs</span>
        </button>
        <button
          type="button"
          class="account-menu-item"
          @click="handleMenuAction(() => logout())"
        >
          <span class="material-symbols-outlined">logout</span>
          <span>Sign Out</span>
        </button>
      </div>
    </div>
  </aside>
</template>

<style scoped>
.thread-item {
  display: flex;
  align-items: center;
  gap: 4px;
  min-height: 34px;
  padding: 0 8px;
  border-radius: 6px;
  transition:
    background 160ms ease,
    color 160ms ease;
}

.thread-item:hover,
.thread-item.active {
  background: var(--surface-low);
}

.thread-item.active .thread-button {
  color: var(--ink);
  font-weight: 600;
}

.thread-button {
  max-width: 100%;
  overflow: hidden;
  border: 0;
  background: transparent;
  color: var(--ink-muted);
  font-size: 14px;
  text-align: left;
  text-overflow: ellipsis;
  white-space: nowrap;
  cursor: pointer;
  flex: 1;
  min-width: 0;
  padding: 7px 0;
}

.thread-button:hover {
  color: var(--ink);
}

.thread-actions {
  display: flex;
  gap: 2px;
  opacity: 0;
  flex-shrink: 0;
  transition: opacity 160ms ease;
}

.thread-item:hover .thread-actions {
  opacity: 1;
}

.thread-action-btn {
  display: grid;
  width: 24px;
  height: 24px;
  place-items: center;
  border: 0;
  border-radius: 4px;
  background: transparent;
  color: var(--ink-soft);
  cursor: pointer;
  transition: background 140ms ease, color 140ms ease;
}

.thread-action-btn:hover {
  background: var(--surface-mid);
  color: var(--ink);
}

.thread-action-delete:hover {
  color: #ba1a1a;
}

.theme-dark .thread-action-delete:hover {
  color: #ffb4ab;
}

.thread-action-btn .material-symbols-outlined {
  font-size: 14px;
}

.thread-edit-input {
  width: 100%;
  padding: 4px 8px;
  border: 1px solid var(--primary);
  border-radius: 4px;
  outline: 0;
  background: var(--surface);
  color: var(--ink);
  font: inherit;
  font-size: 14px;
  line-height: 1.4;
}

.account-section {
  position: relative;
}

.account-menu {
  position: absolute;
  bottom: calc(100% + 4px);
  left: 0;
  right: 0;
  padding: 4px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--surface);
  box-shadow: var(--shadow);
  z-index: 30;
}

.account-menu-item {
  display: flex;
  width: 100%;
  align-items: center;
  gap: 12px;
  padding: 10px 12px;
  border: 0;
  border-radius: 6px;
  background: transparent;
  color: var(--ink);
  font-size: 14px;
  text-align: left;
  cursor: pointer;
  transition: background 140ms ease;
}

.account-menu-item:hover {
  background: var(--surface-low);
}

.account-menu-item .material-symbols-outlined {
  font-size: 18px;
  color: var(--ink-muted);
}
</style>

// frontend/src/components/SideNav.tsx
import { useState, useRef, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '@/hooks/useAuth'
import { useConversations } from '@/hooks/useConversations'
import { useOrbitStore } from '@/stores/useOrbitStore'
import { useClickOutside } from '@/hooks/useClickOutside'
import type { Conversation } from '@/api/types'
import './SideNav.css'

export function SideNav() {
  const { user, hasUser, isBooting, openAuth, logout } = useAuth()
  const {
    sortedConversations,
    activeConversationId,
    formatConversationTitle,
    selectConversation,
    createNewThread,
    renameConversation,
    archiveConversation,
  } = useConversations(hasUser)

  const activeView = useOrbitStore((s) => s.activeView)
  const setActiveView = useOrbitStore((s) => s.setActiveView)
  const navigate = useNavigate()

  const editingThreadId = useOrbitStore((s) => s.editingThreadId)
  const editingTitle = useOrbitStore((s) => s.editingTitle)
  const setEditingThreadId = useOrbitStore((s) => s.setEditingThreadId)
  const setEditingTitle = useOrbitStore((s) => s.setEditingTitle)

  const [showAccountMenu, setShowAccountMenu] = useState(false)
  const editInputRef = useRef<HTMLInputElement>(null)

  const displayName = user?.display_name || user?.email?.split('@')[0] || ''
  const accountInitial = displayName.slice(0, 1).toUpperCase()

  const startRename = useCallback(
    (conversation: { id: string; title?: string | null }, event: React.MouseEvent) => {
      event.stopPropagation()
      setEditingThreadId(conversation.id)
      setEditingTitle(conversation.title || '')
      requestAnimationFrame(() => {
        editInputRef.current?.focus()
        editInputRef.current?.select()
      })
    },
    [setEditingThreadId, setEditingTitle],
  )

  const submitRename = useCallback(async () => {
    const title = editingTitle.trim()
    if (title && editingThreadId) {
      await renameConversation(editingThreadId, title)
    }
    setEditingThreadId(null)
    setEditingTitle('')
  }, [editingTitle, editingThreadId, renameConversation, setEditingThreadId, setEditingTitle])

  const handleNewThread = useCallback(() => {
    if (!user) {
      openAuth()
      return
    }
    setActiveView('chat')
    navigate('/')
    createNewThread()
  }, [createNewThread, navigate, openAuth, setActiveView, user])

  const handleSelectConversation = useCallback(
    (conversationId: string) => {
      setActiveView('chat')
      navigate('/')
      selectConversation(conversationId)
    },
    [navigate, selectConversation, setActiveView],
  )

  const handleOpenLibrary = useCallback(() => {
    setActiveView('library')
    navigate('/library')
  }, [navigate, setActiveView])

  const cancelEdit = useCallback(() => {
    setEditingThreadId(null)
    setEditingTitle('')
  }, [setEditingThreadId, setEditingTitle])

  const handleDelete = useCallback(
    (conversation: Conversation, event: React.MouseEvent) => {
      event.stopPropagation()
      if (!confirm(`Archive "${formatConversationTitle(conversation)}"?`)) return
      archiveConversation(conversation.id)
    },
    [archiveConversation, formatConversationTitle],
  )

  const toggleAccountMenu = useCallback(() => {
    if (!user) {
      openAuth()
      return
    }
    setShowAccountMenu((prev) => !prev)
  }, [user, openAuth])

  const handleMenuAction = useCallback(
    (action: () => void) => {
      setShowAccountMenu(false)
      action()
    },
    [],
  )

  const accountMenuRef = useClickOutside<HTMLDivElement>(
    useCallback(() => setShowAccountMenu(false), []),
  )

  return (
    <aside className="side-nav" aria-label="Primary navigation">
      <div className="brand-panel">
        <h1>Orbit</h1>
        <p>Zen AI Assistant</p>
      </div>

      <div className="nav-action">
        <button type="button" className="primary-button" onClick={handleNewThread}>
          <span className="material-symbols-outlined" aria-hidden="true">add</span>
          <span>New Chat</span>
        </button>
      </div>

      <nav className="nav-list" aria-label="Workspace">
        <div className="thread-section-title">Chats</div>
        <div className="thread-list" aria-label="Recent conversations">
          {sortedConversations.map((conversation) => (
            <div
              key={conversation.id}
              className={`thread-item${conversation.id === activeConversationId ? ' active' : ''}`}
            >
              {editingThreadId === conversation.id ? (
                <input
                  ref={editInputRef}
                  value={editingTitle}
                  onChange={(e) => setEditingTitle(e.target.value)}
                  className="thread-edit-input"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') submitRename()
                    if (e.key === 'Escape') cancelEdit()
                  }}
                  onBlur={submitRename}
                  onClick={(e) => e.stopPropagation()}
                />
              ) : (
                <>
                  <button
                    type="button"
                    className="thread-button"
                    onClick={() => handleSelectConversation(conversation.id)}
                  >
                    {formatConversationTitle(conversation)}
                  </button>
                  <div className="thread-actions">
                    <button
                      type="button"
                      className="thread-action-btn"
                      aria-label="Rename"
                      title="Rename"
                      onClick={(e) => startRename(conversation, e)}
                    >
                      <span className="material-symbols-outlined">edit</span>
                    </button>
                    <button
                      type="button"
                      className="thread-action-btn thread-action-delete"
                      aria-label="Archive"
                      title="Archive"
                      onClick={(e) => handleDelete(conversation, e)}
                    >
                      <span className="material-symbols-outlined">close</span>
                    </button>
                  </div>
                </>
              )}
            </div>
          ))}
          {isBooting && <p>Loading workspace...</p>}
          {!isBooting && !user && <p>Sign in to sync chats</p>}
          {!isBooting && user && sortedConversations.length === 0 && <p>No conversations yet</p>}
        </div>

        <button
          type="button"
          className={`nav-item${activeView === 'library' ? ' active' : ''}`}
          onClick={handleOpenLibrary}
        >
          <span className="material-symbols-outlined" aria-hidden="true">book_2</span>
          <span>Library</span>
        </button>
      </nav>

      <div className="account-section" ref={accountMenuRef}>
        <button type="button" className="account-button" onClick={toggleAccountMenu}>
          <span className="avatar" aria-hidden="true">{user ? accountInitial : '?'}</span>
          <span className="account-copy">
            <strong>{displayName}</strong>
            <small>{user ? 'Sign out' : 'Sign in'}</small>
          </span>
          <span className="material-symbols-outlined" aria-hidden="true">
            {user ? (showAccountMenu ? 'expand_less' : 'expand_more') : 'login'}
          </span>
        </button>

        {showAccountMenu && user && (
          <div className="account-menu">
            <button
              type="button"
              className="account-menu-item"
              onClick={() => handleMenuAction(handleOpenLibrary)}
            >
              <span className="material-symbols-outlined">tune</span>
              <span>LLM Configs</span>
            </button>
            <button
              type="button"
              className="account-menu-item"
              onClick={() => handleMenuAction(() => logout())}
            >
              <span className="material-symbols-outlined">logout</span>
              <span>Sign Out</span>
            </button>
          </div>
        )}
      </div>
    </aside>
  )
}
